services:
  directus:
    image: directus/directus:11.0.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "qwerty12"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      # DB_HOST: localhost
      # DB_PORT: 5173
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_ALLOWED_HEADERS: "http://localhost:5173/"

